### ISSUE TITLE
Determine placement for multi language dropdown in FP app

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-fp#49]
Hi Roger - can you help us by confirming placement for the multi-language dropdown for the FP app? I am suggesting we extend the main menu dropdown on the main register page, with a "Language" option. Tapping on this option opens a dialog in the middle of the screen for the language options. Tapping on the language option of choice selects that language and closes the dialog simultaneously.

What do you think of this suggestion? Might you be able to provide a mockup for the VenD team?  

![Screenshot_20200513-100608_Family_Planning](https://user-images.githubusercontent.com/3488986/81794396-9f1a5e00-9502-11ea-9067-75e9dc5f5d34.jpg)

**Comment by rowo** [comment]
@cafootitt Yes, that'll work. Are they building this now? I thought it wasn't for MVP.

**Comment by rowo** [comment]
See https://marvelapp.com/9c67ab6/screen/67385097/handoff and https://marvelapp.com/9c67ab6/screen/69205599/handoff. 

The label I suggest is "Change language..." rather than "Language". Previously in the hamburger menu, we've used a globe icon and the selected language label i.e. "English". I don't think that works super well for this menu as is.

The dialog should have the language options written in the language's spelling/characters.

**Comment by cafootitt** [comment]
Brilliant, thanks Roger.
